//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinStudio.Test.ServiceCustomer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCustomer.IServiceCustomer")]
    public interface IServiceCustomer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/DoWork", ReplyAction="http://tempuri.org/IServiceCustomer/DoWorkResponse")]
        string DoWork(string account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/DoWork", ReplyAction="http://tempuri.org/IServiceCustomer/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync(string account);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCustomerChannel : WinStudio.Test.ServiceCustomer.IServiceCustomer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCustomerClient : System.ServiceModel.ClientBase<WinStudio.Test.ServiceCustomer.IServiceCustomer>, WinStudio.Test.ServiceCustomer.IServiceCustomer {
        
        public ServiceCustomerClient() {
        }
        
        public ServiceCustomerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCustomerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork(string account) {
            return base.Channel.DoWork(account);
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync(string account) {
            return base.Channel.DoWorkAsync(account);
        }
    }
}
